# Generated by Django 2.2.5 on 2020-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('targetURL', models.CharField(max_length=1000)),
                ('shortenedURL', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
