# Generated by Django 2.2.5 on 2020-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_url_length', models.IntegerField(default=5)),
                ('max_url_length', models.IntegerField(default=10)),
                ('allow_uppercase', models.BooleanField(default=True)),
                ('allow_lowercase', models.BooleanField(default=True)),
                ('allow_digits', models.BooleanField(default=True)),
                ('myDomain', models.CharField(default='http://localhost:8000/', max_length=100)),
                ('prefix', models.CharField(default='', max_length=100)),
                ('suffix', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='shortenedURL',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
