# Generated by Django 2.2.5 on 2020-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200715_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
